FROM maven:3.6.0-jdk-8-alpine as builder
WORKDIR './app'
COPY pom.xml .
RUN mvn dependency:resolve
COPY . .
RUN java -jar target/mock-trader-0.0.1-SNAPSHOT.jar

FROM openjdk:8-jre
COPY --from=builder ./target/mock-trader-0.0.1-SNAPSHOT.jar ./
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","mock-trader-0.0.1-SNAPSHOT.jar"]
