dependencies:
- name: pipeline-cluster-monitor
  repository: http://kubernetes-charts.banzaicloud.com/branch/master
  version: '>=0.1.10'
  alias: monitor
  condition: monitor.enabled
- name: pipeline-cluster-ingress
  repository: http://kubernetes-charts.banzaicloud.com/branch/master
  version: '>=0.0.6'
  alias: ingress
  condition: ingress.enabled
- name: mongodb
  repository: '@stable'
  version: 4.8.3
  alias: mongodb
  condition: mongodb.enabled
